[project]
name = "bielemetrics"
version = "0.1.0"
description = ""
authors = []
requires-python = ">=3.13"

dependencies = [
    "pyarrow",
    "pandas",
    "numpy",
    "matplotlib",
    "scikit-learn",
    "shapely",
    "tqdm",
    "python-dotenv",
    "kinexon-handball-api",
    "sportradar-datacore-api",
    "duckdb>=1.4.1",
    "plotly>=6.4.0",
    "opencv-python>=4.11.0.86",
    "dagster>=1.12.2",
    "dagster-webserver>=1.12.2",
    "dagster-duckdb>=0.28.2",
    "thefuzz>=0.22.1",
    "seaborn>=0.13.2",
    "xgboost>=3.1.2",
    "pre-commit>=4.5.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
kinexon-handball-api = { path = "../KinexonHandballAPI" }
sportradar-datacore-api = { path = "../SportradarDatacoreAPI" }


[tool.pylint.'MESSAGES CONTROL']
disable = ["relative-beyond-top-level", "E402"]
